export const VIEW_RESUME = "VIEW_RESUME";
export const VIEW_RESUME_SUCCESS = "VIEW_RESUME_SUCCESS";
export const VIEW_RESUME_ERROR = "VIEW_RESUME_ERROR";

export const CREATE_RESUME = "CREATE_RESUME";
export const CREATE_RESUME_SUCCESS = "CREATE_RESUME_SUCCESS";
export const CREATE_RESUME_ERROR = "CREATE_RESUME_ERROR";

export const UPDATE_RESUME = "UPDATE_RESUME";
export const UPDATE_RESUME_SUCCESS = "UPDATE_RESUME_SUCCESS";
export const UPDATE_RESUME_ERROR = "UPDATE_RESUME_ERROR";

export const VIEW_CV = "VIEW_CV";
export const VIEW_CV_SUCCESS = "VIEW_CV_SUCCESS";
export const VIEW_CV_ERROR = "VIEW_CV_ERROR";

export const CREATE_CV = "CREATE_CV";
export const CREATE_CV_SUCCESS = "CREATE_CV_SUCCESS";
export const CREATE_CV_ERROR = "CREATE_CV_ERROR";

export const UPDATE_CV = "UPDATE_CV";
export const UPDATE_CV_SUCCESS = "UPDATE_CV_SUCCESS";
export const UPDATE_CV_ERROR = "UPDATE_CV_ERROR";
