export const EMPLOYERS = "EMPLOYERS"
export const EMPLOYERS_SUCCESS = "EMPLOYERS_SUCCESS"
export const EMPLOYERS_ERROR = "EMPLOYERS_ERROR"

export const JOBSEEKER = "JOBSEEKER"
export const JOBSEEKER_SUCCESS = "JOBSEEKER_SUCCESS"
export const JOBSEEKER_ERROR = "JOBSEEKER_ERROR"

export const UPDATE_PROILE = 'UPDATE_PROFILE'
export const UPDATE_PROILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROILE_ERROR = 'UPDATE_PROFILE_ERROR'