

export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_SUCCESSFUL = "REGISTER_USER_SUCCESSFUL"
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED"
export const RESET_REGISTER_FLAG = "RESET_REGISTER_FLAG";

export const SIGN_UP = "SIGN_UP"
export const SIGN_UP_ERROR = "SIGN_UP_ERROR"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"

export const ACTIVATE_USER = "ACTIVATE_USER"
export const ACTIVATE_USER_SUCCESS = "ACTIVATE_USER_SUCCESS"
export const ACTIVATE_USER_ERROR = "ACTIVATE_USER_ERROR"

export const REDIRECT_TO_ROUTE = 'REDIRECT_TO_ROUTE';

export const RESEND_ACTIVATION_CODE = "RESEND_ACTIVATION_CODE"
export const RESEND_ACTIVATION_CODE_SUCCESS = "RESEND_ACTIVATION_CODE_SUCCESS"
export const RESEND_ACTIVATION_CODE_ERROR = "RESEND_ACTIVATION_CODE_ERROR"