export const INVOICE = "INVOICE"
export const INVOICE_SUCCESS = "INVOICE_SUCCESS"
export const INVOICE_ERROR = "INVOICE_ERROR"

export const UPDATE_INVOICE = "UPDATE_INVOICE"
export const UPDATE_INVOICE_SUCCESS = "UPDATE_INVOICE_SUCCESS"
export const UPDATE_INVOICE_ERROR = "UPDATE_INVOICE_ERROR"

export const CREATE_INVOICE = "CREATE_INVOICE"
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS"
export const CREATE_INVOICE_ERROR = "CREATE_INVOICE_ERROR"

export const INVOICE_PAYMENT = "INVOICE_PAYMENT"
export const INVOICE_PAYMENT_SUCCESS = "INVOICE_PAYMENT_SUCCESS"
export const INVOICE_PAYMENT_ERROR = "INVOICE_PAYMENT_ERROR"