export const SAVE_FEEDS = "SAVE_FEEDS"
export const SAVE_FEEDS_SUCCESS = "SAVE_FEEDS_SUCCESS"
export const SAVE_FEEDS_ERROR = "SAVE_FEEDS_ERROR"

export const SAVE_USER_FEED = "SAVE_USER_FEED"
export const SAVE_USER_FEED_SUCCESS = "SAVE_USER_FEED_SUCCESS"
export const SAVE_USER_FEED_ERROR = "SAVE_USER_FEED_ERROR"

export const UPDATE_FEEDS = "UPDATE_FEEDS"
export const UPDATE_FEEDS_SUCCESS = "UPDATE_FEEDS_SUCCESS"
export const UPDATE_FEEDS_ERROR = "UPDATE_FEEDS_ERROR"

export const UPDATE_USER_FEEDS = "UPDATE_USER_FEEDS"
export const UPDATE_USER_FEEDS_SUCCESS = "UPDATE_USER_FEEDS_SUCCESS"
export const UPDATE_USER_FEEDS_ERROR = "UPDATE_USER_FEEDS_ERROR"

export const FEEDS = "FEEDS"
export const FEEDS_SUCCESS = "FEEDS_SUCCESS"
export const FEEDS_ERROR = "FEEDS_ERROR"

export const APPROVE_FEEDS = "APPROVE_FEEDS"
export const APPROVE_FEEDS_SUCCESS = "APPROVE_FEEDS_SUCCESS"
export const APPROVE_FEEDS_ERROR = "APPROVE_FEEDS_ERROR"

export const MY_FEEDS = "MY_FEEDS"
export const MY_FEEDS_SUCCESS = "MY_FEEDS_SUCCESS"
export const MY_FEEDS_ERROR = "MY_FEEDS_ERROR"

export const VIEW_SINGLE_MANUAL_FEED = "VIEW_SINGLE_MANUAL_FEED"
export const VIEW_SINGLE_MANUAL_FEED_SUCCESS = "VIEW_SINGLE_MANUAL_FEED_SUCCESS"
export const VIEW_SINGLE_MANUAL_FEED_ERROR = "VIEW_SINGLE_MANUAL_FEED_ERROR"

export const FETCH_NEWS = "FETCH_NEWS"
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS"
export const FETCH_NEWS_ERROR = "FETCH_NEWS_ERROR"