export const RATE_CARD = "RATE_CARD"
export const RATE_CARD_SUCCESS = "RATE_CARD_SUCCESS"
export const RATE_CARD_ERROR = "RATE_CARD_ERROR"

export const APPROVE_RATE_CARD = "APPROVE_RATE_CARD"
export const APPROVE_RATE_CARD_SUCCESS = "APPROVE_RATE_CARD_SUCCESS"
export const APPROVE_RATE_CARD_ERROR = "APPROVE_RATE_CARD_ERROR"

export const CREATE_RATE_CARD = "CREATE_RATE_CARD"
export const CREATE_RATE_CARD_SUCCESS = "CREATE_RATE_CARD_SUCCESS"
export const CREATE_RATE_CARD_ERROR = "CREATE_RATE_CARD_ERROR"

export const UPDATE_RATE_CARD = "UPDATE_RATE_CARD"
export const UPDATE_RATE_CARD_ERROR = "UPDATE_RATE_CARD_ERROR"
export const UPDATE_RATE_CARD_SUCCESS = "UPDATE_RATE_CARD_SUCCESS"


export const PAY = "PAY"
export const PAY_SUCCESS = "PAY_SUCCESS"
export const PAY_ERROR = "PAY_ERROR"