export const INDUSTRY = "INDUSTRY";
export const INDUSTRY_ERROR = "INDUSTRY_ERRROR";
export const INDUSTRY_SUCCESS = "INDUSTRY_SUCCESS";

export const GENERAL_INDUSTRIES = "GENERAL_INDUSTRIES";
export const GENERAL_INDUSTRIES_ERROR = "GENERAL_INDUSTRIES_ERRROR";
export const GENERAL_INDUSTRIES_SUCCESS = "GENERAL_INDUSTRIES_SUCCESS";

export const CREATE_INDUSTRY = "CREATE_INDUSTRY";
export const CREATE_INDUSTRY_ERROR = "CREATE_INDUSTRY_ERROR";
export const CREATE_INDUSTRY_SUCCESS = "CREATE_INDUSTRY_SUCCESS";

export const UPDATE_INDUSTRY = "UPDATE_INDUSTRY";
export const UPDATE_INDUSTRY_ERROR = "UPDATE_INDUSTRY_ERROR";
export const UPDATE_INDUSTRY_SUCCESS = "UPDATE_INDUSTRY_SUCCESS";

export const CATEGORY = "CATEGORY";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";

export const GENERAL_CATEGORIES = "GENERAL_CATEGORIES";
export const GENERAL_CATEGORIES_ERROR = "GENERAL_CATEGORIES_ERROR";
export const GENERAL_CATEGORIES_SUCCESS = "GENERAL_CATEGORIES_SUCCESS";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
