export const CREATE_JOB_STATUS = "CREATE_JOB_STATUS"
export const CREATE_JOB_STATUS_SUCCESS = "CREATE_JOB_STATUS_SUCCESS"
export const CREATE_JOB_STATUS_ERROR = "CREATE_JOB_STATUS_ERROR"

export const JOB_STATUS = "JOB_STATUS"
export const JOB_STATUS_SUCCESS = "JOB_STATUS_SUCCESS"
export const JOB_STATUS_ERROR = "JOB_STATUS_ERROR"

export const UPDATE_JOB_STATUS = "UPDATE_JOB_STATUS"
export const UPDATE_JOB_STATUS_SUCCESS = "UPDATE_JOB_STATUS_SUCCESS"
export const UPDATE_JOB_STATUS_ERROR = "UPDATE_JOB_STATUS_ERROR"

export const CREATE_JOB = "CREATE_JOB"
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS"
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR"

export const UPDATE_JOB = "UPDATE_JOB"
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS"
export const UPDATE_JOB_ERROR = "UPDATE_JOB_ERROR"

export const JOBS = "JOBS"
export const JOBS_SUCCESS = "JOBS_SUCCESS"
export const JOBS_ERROR = "JOBS_ERROR"

export const APPROVE_JOBS = "APPROVE_JOBS"
export const APPROVE_JOBS_SUCCESS = "APPROVE_JOBS_SUCCESS"
export const APPROVE_JOBS_ERROR = "APPROVE_JOBS_ERROR"