export const VIEW_JOB_ALERTS = "VIEW_JOB_ALERTS";
export const VIEW_JOB_ALERTS_ERROR = "VIEW_JOB_ALERTS_ERROR";
export const VIEW_JOB_ALERTS_SUCCESS = "VIEW_JOB_ALERTS_SUCCESS";

export const VIEW_SAVED_JOBS = "VIEW_SAVED_JOBS";
export const VIEW_SAVED_JOBS_SUCCESS = "VIEW_SAVED_JOBS_SUCCESS";
export const VIEW_SAVED_JOBS_ERROR = "VIEW_SAVED_JOBS_ERROR";

export const CREATE_JOB_ALERT = "CREATE_JOB_ALERT"; 
export const CREATE_JOB_ALERT_SUCCESS = "CREATE_JOB_ALERT_SUCCESS"; 
export const CREATE_JOB_ALERT_ERROR = "CREATE_JOB_ALERT_ERROR"; 

export const UPDATE_JOB_ALERT = "UPDATE_JOB_ALERT"
export const UPDATE_JOB_ALERT_SUCCESS = "UPDATE_JOB_ALERT_SUCCESS"
export const UPDATE_JOB_ALERT_ERROR = "UPDATE_JOB_ALERT_ERROR"

export const SAVE_JOBS = "SAVE_JOBS"
export const SAVE_JOBS_SUCCESS = "SAVE_JOBS_SUCCESS"
export const SAVE_JOBS_ERROR = "SAVE_JOBS_ERROR"

export const UPDATE_SAVED_JOBS = "UPDATE_SAVED_JOBS"
export const UPDATE_SAVED_JOBS_SUCCESS = "UPDATE_SAVED_JOBS_SUCCESS"
export const UPDATE_SAVED_JOBS_ERROR = "UPDATE_SAVED_JOBS_ERROR"

export const FULL_JOB_DETAILS = "FULL_JOB_DETAILS"
export const FULL_JOB_DETAILS_SUCCESS = "FULL_JOB_DETAILS_SUCCESS"
export const FULL_JOB_DETAILS_ERROR = "FULL_JOB_DETAILS_ERROR"

export const FIND_JOB = "FIND_JOB"
export const FIND_JOB_SUCCESS = "FIND_JOB_SUCCESS"
export const FIND_JOB_ERROR = "FIND_JOB_ERROR"

export const APPLY_FOR_JOBS = "APPLY_FOR_JOBS"
export const APPLY_FOR_JOBS_SUCCESS = "APPLY_FOR_JOBS_SUCCESS"
export const APPLY_FOR_JOBS_ERROR = "APPLY_FOR_JOBS_ERROR"


