export const VIEW_JOB_ALERTS = "VIEW_JOB_ALERTS";
export const VIEW_JOB_ALERTS_ERROR = "VIEW_JOB_ALERTS_ERROR";
export const VIEW_JOB_ALERTS_SUCCESS = "VIEW_JOB_ALERTS_SUCCESS";

export const VIEW_SAVED_JOBS = "VIEW_SAVED_JOBS";
export const VIEW_SAVED_JOBS_SUCCESS = "VIEW_SAVED_JOBS_SUCCESS";
export const VIEW_SAVED_JOBS_ERROR = "VIEW_SAVED_JOBS_ERROR";

export const CREATE_JOB_ALERT = "CREATE_JOB_ALERT"; 
export const CREATE_JOB_ALERT_SUCCESS = "CREATE_JOB_ALERT_SUCCESS"; 
export const CREATE_JOB_ALERT_ERROR = "CREATE_JOB_ALERT_ERROR"; 

export const UPDATE_JOB_ALERT = "UPDATE_JOB_ALERT"
export const UPDATE_JOB_ALERT_SUCCESS = "UPDATE_JOB_ALERT_SUCCESS"
export const UPDATE_JOB_ALERT_ERROR = "UPDATE_JOB_ALERT_ERROR"