export const CREATE_QUESTION = "CREATE_QUESTION"
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS"
export const CREATE_QUESTION_ERROR = "CREATE_QUESTION_ERROR"

export const CREATE_QUESTION_Y_N = "CREATE_QUESTION_Y_N"
export const CREATE_QUESTION_Y_N_SUCCESS = "CREATE_QUESTION_Y_N_SUCCESS"
export const CREATE_QUESTION_Y_N_ERROR = "CREATE_QUESTION_Y_N_ERROR"


export const CREATE_QUESTION_SINGLE = "CREATE_QUESTION_SINGLE"
export const CREATE_QUESTION_SINGLE_SUCCESS = "CREATE_QUESTION_SINGLE_SUCCESS"
export const CREATE_QUESTION_SINGLE_ERROR = "CREATE_QUESTION_SINGLE_ERROR"

export const CREATE_QUESTION_MULTIPLE_ERROR = "CREATE_QUESTION_MULTIPLE_ERROR"
export const CREATE_QUESTION_MULTIPLE_SUCCESS = "CREATE_QUESTION_MULTIPLE_SUCCESS"
export const CREATE_QUESTION_MULTIPLE = "CREATE_QUESTION_MULTIPLE"

export const CREATE_QUESTION_RANGE = "CREATE_QUESTION_RANGE"
export const CREATE_QUESTION_RANGE_SUCCESS = "CREATE_QUESTION_RANGE_SUCCESS"
export const CREATE_QUESTION_RANGE_ERROR = "CREATE_QUESTION_RANGE_ERROR"

export const CREATE_JOB_QUESTION = "CREATE_JOB_QUESTION"
export const CREATE_JOB_QUESTION_SUCCESS = "CREATE_JOB_QUESTION_SUCCESS"
export const CREATE_JOB_QUESTION_ERROR = "CREATE_JOB_QUESTION_ERROR"

export const UNLINK_JOB_QUESTION = "UNLINK_JOB_QUESTION"
export const UNLINK_JOB_QUESTION_SUCCESS = "UNLINK_JOB_QUESTION_SUCCESS"
export const UNLINK_JOB_QUESTION_ERROR = "UNLINK_JOB_QUESTION_ERROR"

export const LINK_JOB_QUESTION = "LINK_JOB_QUESTION"
export const LINK_JOB_QUESTION_SUCCESS = "LINK_JOB_QUESTION_SUCCESS"
export const LINK_JOB_QUESTION_ERROR = "LINK_JOB_QUESTION_ERROR"

export const VIEW_MY_QUESTIONS = "VIEW_MY_QUESTIONS"
export const VIEW_MY_QUESTIONS_SUCCESS = "VIEW_MY_QUESTIONS_SUCCESS"
export const VIEW_MY_QUESTIONS_ERROR = "VIEW_MY_QUESTIONS_ERROR"






